[
    {
        "asignatura": "asignatura 1",
        id: 1,
        "asignaturaCode": "A001-G023-F008-U021",
        "universidad": "Universidad de Zaragoza",
        "abreviaturaUniversidad": "UNIZAR",
        "facultad": "Escuela Universitaria Politécnica De Teruel ",
        "grado": "Grado En Ingeniería Informática",
        "precioBN": 4,
        "precioCO": 5.55,
        "nota": 8.5,
        "profesor": "prueba infor 3",
        "editor": "Oscar Alfonso Chesaxddddddd",
        "curso": "1º Curso",
        "cursoId": "65",
    },
    {
        "asignatura": "asignatura 2",
        id: 2,
        "asignaturaCode": "A001-G023-F008-U021",
        "universidad": "Universidad de Zaragoza",
        "abreviaturaUniversidad": "UNIZAR",
        "facultad": "Escuela Universitaria Politécnica De Teruel ",
        "grado": "Grado En Ingeniería Informática",
        "precioBN": 4,
        "precioCO": 5.55,
        "nota": 8.5,
        "profesor": "prueba infor 3",
        "editor": "Oscar Alfonso Chesaxddddddd",
        "curso": "2º Curso",
        "cursoId": "65",
    },
    {
        "asignatura": "asignatura 3",
        id: 3,
        "asignaturaCode": "A001-G023-F008-U021",
        "universidad": "Universidad de Zaragoza",
        "abreviaturaUniversidad": "UNIZAR",
        "facultad": "Escuela Universitaria Politécnica De Teruel ",
        "grado": "Grado En Ingeniería Informática",
        "precioBN": 4,
        "precioCO": 5.55,
        "nota": 8.5,
        "profesor": "prueba infor 3",
        "editor": "Oscar Alfonso Chesaxddddddd",
        "curso": "3º Curso",
        "cursoId": "65",
    }, {
        "asignatura": "asignatura 4",
        id: 4,
        "asignaturaCode": "A001-G023-F008-U021",
        "universidad": "Universidad de Zaragoza",
        "abreviaturaUniversidad": "UNIZAR",
        "facultad": "Escuela Universitaria Politécnica De Teruel ",
        "grado": "Grado En Ingeniería Informática",
        "precioBN": 4,
        "precioCO": 5.55,
        "nota": 8.5,
        "profesor": "prueba infor 3",
        "editor": "Oscar Alfonso Chesaxddddddd",
        "curso": "4º Curso",
        "cursoId": "65",
    },
    {
        "asignatura": "asignatura 5",
        id: 5,
        "asignaturaCode": "A001-G023-F008-U021",
        "universidad": "Universidad de Zaragoza",
        "abreviaturaUniversidad": "UNIZAR",
        "facultad": "Escuela Universitaria Politécnica De Teruel ",
        "grado": "Grado En Ingeniería Informática",
        "precioBN": 4,
        "precioCO": 5.55,
        "nota": 8.5,
        "profesor": "prueba infor 3",
        "editor": "Oscar Alfonso Chesaxddddddd",
        "curso": "5º Curso",
        "cursoId": "65",
    },
    {
        "asignatura": "asignatura 6",
        id: 6,
        "asignaturaCode": "A001-G023-F008-U021",
        "universidad": "Universidad de Zaragoza",
        "abreviaturaUniversidad": "UNIZAR",
        "facultad": "Escuela Universitaria Politécnica De Teruel ",
        "grado": "Grado En Ingeniería Informática",
        "precioBN": 4,
        "precioCO": 5.55,
        "nota": 8.5,
        "profesor": "prueba infor 3",
        "editor": "Oscar Alfonso Chesaxddddddd",
        "curso": "6º Curso",
        "cursoId": "65",
    },
]